version: "3.8"

services:
  #Postgresql
  todoDB:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_app
    ports:
      - "5433:5432"
    volumes:
      - todoDB_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todoApp-network

volumes:
  todoDB_data:

networks:
  todoApp-network:
    driver: bridge
